/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import controller.RdvJpaController;
import controller.PatientsJpaController;
import controller.PersonnesJpaController;
import controller.DocteurJpaController;
import controller.exceptions.IllegalOrphanException;
import controller.exceptions.NonexistentEntityException;
import model.Patients;
import model.Docteur;
import model.Personnes;
import model.Rdv;


/**
 *
 * @author pc
 */
public class addIT extends javax.swing.JFrame {

    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("bdprojecct_PU");
    private final RdvJpaController rdvCtrl = new RdvJpaController(emfac);
    private final PatientsJpaController patientsCtrl = new PatientsJpaController(emfac);
    private final DocteurJpaController docteurCtrl = new DocteurJpaController(emfac);
    private final PersonnesJpaController personnesCtrl = new PersonnesJpaController(emfac);
    /*dd-M-yyyy hh:mm:ss*/
    private final SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
    private final SimpleDateFormat fmt1 = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    
    private static final Logger LOGGER = LogManager.getLogger(AddRdvWindow.class.getName());
    
    Rdv rdv = null;
    
    /**
     * Creates new form addIT
     */
    public addIT() {
        LOGGER.info("Displaying main window");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddPatientsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddDocteurButton = new javax.swing.JButton();
        ListPatientsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList<>();
        ListDocteurButton = new javax.swing.JButton();
        ListRdvButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddRdvButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Add RDV");

        AddPatientsButton.setText("Patients");
        AddPatientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientsButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Click to Add a:");

        jLabel3.setText("Click to add a:");

        AddDocteurButton.setText("Doctor");
        AddDocteurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDocteurButtonActionPerformed(evt);
            }
        });

        ListPatientsButton.setText("ListPatients");
        ListPatientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPatientsButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(itemsList);

        ListDocteurButton.setText("ListDocteur");
        ListDocteurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListDocteurButtonActionPerformed(evt);
            }
        });

        ListRdvButton.setText("ListRDV");
        ListRdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRdvButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Click to add a:");

        AddRdvButton.setText("RDV");
        AddRdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRdvButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddPatientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ListDocteurButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ListPatientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ListRdvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AddRdvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AddDocteurButton, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPatientsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AddDocteurButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AddRdvButton))
                .addGap(21, 21, 21)
                .addComponent(ListRdvButton)
                .addGap(18, 18, 18)
                .addComponent(ListPatientsButton)
                .addGap(18, 18, 18)
                .addComponent(ListDocteurButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientsButtonActionPerformed
        // TODO add your handling code here:
        AddPatientsWindow patientsAddPopup = new AddPatientsWindow();
        patientsAddPopup.setVisible(true);
    }//GEN-LAST:event_AddPatientsButtonActionPerformed

    private void AddDocteurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDocteurButtonActionPerformed
        // TODO add your handling code here:
        AddDocteurWindow docteurAddPopup = new AddDocteurWindow();
        docteurAddPopup.setVisible(true);
    }//GEN-LAST:event_AddDocteurButtonActionPerformed
    
    private void refreshPatientsList(){
        List patients = patientsCtrl.findPatientsEntities();
        EntityListModel<Patients> model = new EntityListModel(patients);
        
        itemsList.setModel(model);
    }
    private void ListPatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPatientsButtonActionPerformed
        // TODO add your handling code here:
        refreshPatientsList();
    }//GEN-LAST:event_ListPatientsButtonActionPerformed
    
    
    private void refreshDocteurList(){
        List docteur = docteurCtrl.findDocteurEntities();
        EntityListModel<Docteur> model = new EntityListModel(docteur);
        
        itemsList.setModel(model);
    }
    private void ListDocteurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListDocteurButtonActionPerformed
        // TODO add your handling code here:
        refreshDocteurList();
    }//GEN-LAST:event_ListDocteurButtonActionPerformed
    
    
    
    private void AddRdvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRdvButtonActionPerformed
        // TODO add your handling code here:
        AddRdvWindow rdvAddPopup = new AddRdvWindow();
        rdvAddPopup.setVisible(true);
    }//GEN-LAST:event_AddRdvButtonActionPerformed

    private void refreshRdvList(){
        List rdv = rdvCtrl.findRdvEntities();
        EntityListModel<Rdv> model = new EntityListModel(rdv);
        
        itemsList.setModel(model);
    }
    private void ListRdvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRdvButtonActionPerformed
        // TODO add your handling code here:
        refreshRdvList();
    }//GEN-LAST:event_ListRdvButtonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LOGGER.info("Displaying main window");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDocteurButton;
    private javax.swing.JButton AddPatientsButton;
    private javax.swing.JButton AddRdvButton;
    private javax.swing.JButton ListDocteurButton;
    private javax.swing.JButton ListPatientsButton;
    private javax.swing.JButton ListRdvButton;
    private javax.swing.JList<String> itemsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
